- name: Play level Variables
  hosts: local
  connection: local 
  vars_files:
  - course.yaml
  tasks:
  - name: print the cousre info
    ansible.builtin.debug:  
      msg: "Course Name is: {{ COURSE }}, DUration: {{ DURATION }}, Trainer: {{ TRAINER}}"

