- name: string to list
  hosts: local
  connection: local
  vars:
    technologies: DevOps, AWS, Ansible, Linux
    tags:
      application: payment
      env: dev
    listdepart:
    - key: senior
      value: Analayst
    - key: Associate
      value: consultant
    name: praveena Palla
    gmail: Info@gmail.com
    Ipadress: 355.168.1.0 # max ipadress 255.255.255.255

       
  tasks:
  - name: converting string to list
    ansible.builtin.debug:
     msg: "Technologies are : {{technologies | split(',') }}"
  - name: converting map to lsist
    ansible.builtin.debug:
      msg: "tages are: {{tags | dict2items}}"
  
  - name: converting lsit to map
    ansible.builtin.debug:
      msg: "tages are: {{ listdepart | items2dict }}"

  - name: read yaml ad take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}" 
  
  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json:{{ student_yaml | to_json}}"
  
  - name: save json to a file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json}}"
  - name: convert to upper case
    ansible.builtin.debug:
      msg: "{{gmail | upper}}"
  - name: convert to lower case
    ansible.builtin.debug:
      msg: "{{name | lower}}"
  - name: check Ip adress is valid or Not 
    ansible.builtin.debug: 
       msg: "{{ Ipadress | ansible.utils.ipv4 }}"


  # shell Vs command
  #  remote login -> take login, execute command an dc omeout

  #  or login inside the sercver and execute the command
  #   when we dont have readymade modiules avaibale, we can execute  command or shell modele

  #   command-> a simple command no need of acess to shell environment like varibales , absh , piping, etc;;
  #   shell module -> can acess variables, pipes shel environments etc


  # - name: grep for root
  #   ansible.builtin.command: cat /etc/passwd | grep root
  #   register: command_ouput # execute ayina command value ne teesukovali andte register and vaalue stores in command_output
  # - name: print the command_output
  #   ansible.builtin.debug:
  #     msg: "{{ command_output }}"  # here we will get error as it is complex commands so we need to use shell module instead of command module

  - name: grep for root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_ouput 

  - name: print the command_ouput
    ansible.builtin.debug:
      msg: "{{ command_ouput }}" 

  ## redirections
  - name: redirect the command_output
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    register: redirect_output
  - name: print the redirect_output
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"
