- name: string to list
  hosts: local
  connection: local
  vars:
    technologies: DevOps, AWS, Ansible, Linux
    tags:
      application: payment
      env: dev
    listdepart:
    - key: senior
      value: Analayst
    - key: Associate
      value: consultant

       
  tasks:
  - name: converting string to list
    ansible.builtin.debug:
     msg: "Technologies are : {{technologies | split(',') }}"
  - name: converting map to lsist
    ansible.builtin.debug:
      msg: "tages are: {{tags | dict2items}}"
  
  - name: converting lsit to map
    ansible.builtin.debug:
      msg: "tages are: {{ listdepart | items2dict }}"

  - name: read yaml ad take it into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}" 
  
  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json:{{ student_yaml | to_json}}"
  
  - name: save json to a file
    ansible.buitlin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json}}"
